version: "3"
services:
  bangumi:
    container_name: bangumi
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: bangumi_explorer:latest
    ports: 
      - 3001:3000
    volumes:
      - type: bind
        source: ./output
        target: /database
      - type: bind
        source: ./.data
        target: /anime
        read_only: true
